# #######################################################################################
# HYPRLAND MODULAR CONFIG (DEBIAN 13 TRIXIE)
# #######################################################################################

# --- MODULES LOADING ---
# This line loads all files from the conf.d directory in numeric order
source = ~/.config/hypr/conf.d/*.conf

# --- MONITORS ---
# See https://wiki.hypr.land/Configuring/Monitors/
monitor=,preferred,auto,auto

# --- DEFAULT PROGRAMS ---
$terminal = kitty
$fileManager = thunar
$menu = hyprlauncher

# --- MISC ---
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

debug {
    disable_logs = false
}
