windowrule {
    name = suppress-maximize
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = xwayland-no-focus
    match:xwayland = true
    match:float = true
    no_focus = true
}

windowrule {
    name = hyprland-run-float
    match:class = ^(hyprland-run)$
    float = true
}

windowrule {
    name = thunar-float-center
    match:class = ^(thunar)$
    float = true
    center = true
    size = 900 600
}
windowrule {
    name = portal-filepicker
    match:class = ^(xdg-desktop-portal-gtk)$
    float = true
    center = true
    size = 900 600
}
