#################
### AUTOSTART ###
#################

# System services
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/bin/lxqt-policykit-agent
exec-once = dunst
exec-once = waybar

# Wallpaper and tools
exec-once = hyprpaper
